spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
  threads:
    virtual:
      enabled: true

mybatis:
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

dohmap:
  jobs:
    full-run: 0 0 22 * * 5
    lite-run: 0 0 22 * * 1-4
