spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
  threads:
    virtual:
      enabled: true

mybatis:
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

management:
  server:
    port: 9101
  endpoints:
    web:
      exposure:
        include: health, prometheus
      base-path: "/"
      path-mapping:
        prometheus: "metrics"

dohmap:
  jobs:
    full-run: 0 0 22 * * 5
    lite-run: 0 0 22 * * 1-4
  google-maps:
    allowed-establishment-types: Restaurants,Beverage,Breakfast,Food Permit
  city-mappings:
    ['AMERIAN FORK']: AMERICAN FORK
    ['CEDER HILLS']: CEDAR HILLS
    ['COPPERTON TS']: COPPERTON
    ['EAGLE MTN']: EAGLE MOUNTAIN
    ['KEARNS TS']: KEARNS
    ['MILLCREEK TS']: MILLCREEK
    ['PLEASANTE GROVE']: PLEASANT GROVE
    ['PLEASANT GROVCE']: PLEASANT GROVE
    ['PLEASAT GROVE']: PLEASANT GROVE
    ['PROVO CANYON']: PROVO

springdoc:
  paths-to-exclude: '/api/admin/**'