spring:
  datasource:
    username: dohmap
    password: password
    url: jdbc:postgresql://127.0.0.1/postgres?currentSchema=schema
  thymeleaf:
    cache: false
  security:
    user.name: admin
    user.password: admin
    user.roles: ADMIN

server:
  port: 5678

dohmap:
  google-maps:
    api-key: gmap-api-key-here
    use-places-api: false
  selenium:
    sessions: 2
    remote: http://grid-url:4444
    # headless may not be needed for remote selenium sessions
    args: >
      --headless=new
  # these are separate incase they need to be different
  origin: https://dohmap.com
  url: https://dohmap.com
  about-page: >
    <h1>About DOH Map!</h1>
    <p>Default about page!</p>
