spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
  threads:
    virtual:
      enabled: true

mybatis:
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
